/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.JLogoApp.app;

import static it.unicam.cs.pa.JLogoApp.utilities.StringUtils.join;
import static it.unicam.cs.pa.JLogoApp.utilities.StringUtils.split;
import static it.unicam.cs.pa.JLogoApp.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import java.util.LinkedList;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
